### ISSUE TITLE
DGX 4480 - Nightly Benchmark run 4480-20210204

### ISSUE THREAD

**Issue by quasiben** [quasiben/dask-scheduler-performance#102]
## Benchmark history
<img width="641" alt="Benchmark Image"
src="https://raw.githubusercontent.com/quasiben/dask-scheduler-performance/benchmark-images/assets/dgx-4480-20210204-benchmark-history.png">

## Raw Data
<Client: 'tcp://127.0.0.1:34013' processes=10 threads=10, memory=540.94 GB>
Distributed Version: 2021.01.1+14.ga0d60e7b
simple
	 5.475e-01 +/- 4.27e-02
shuffle
	 2.256e+01 +/- 1.009e+00
rand_access
	 1.041e-02 +/- 1.329e-03
anom_mean
	 9.949e+01 +/- 8.054e-01

## Raw Values
simple
	 [0.58701086 0.52487779 0.50652409 0.51683784 0.58730984 0.53589463
 0.62814784 0.47800493 0.56864429 0.54135227]
shuffle
	 [23.61287832 23.79913616 21.81883407 21.01972342 21.4097302  22.95353341
 21.96969128 23.51331043 21.81375837 23.70815349]
rand_access
	 [0.00773001 0.00953388 0.01086974 0.01190329 0.01062369 0.01146913
 0.00869823 0.01183629 0.01141453 0.01006341]
anom_mean
	 [ 98.67475772  99.0814085   99.3625977   98.47209287  99.49914122
  98.5962007  100.6324234   99.86433983 101.00307035  99.75229931]

## Dask Profiles

- [Shuffle
 Profile](https://raw.githack.com/quasiben/dask-scheduler-performance/benchmark-images/assets/4480-20210204-shuffle-scheduler.html)
- [Random Access
  Profile](https://raw.githack.com/quasiben/dask-scheduler-performance/benchmark-images/assets/4480-20210204-rand-access-scheduler.html)
- [Simple
  Profile](https://raw.githack.com/quasiben/dask-scheduler-performance/benchmark-images/assets/4480-20210204-simple-scheduler.html)
- [Anom
  Mean](https://raw.githack.com/quasiben/dask-scheduler-performance/benchmark-images/assets/4480-20210204-anom-mean-scheduler.html)

## Scheduler Execution Graph
<img width="641" alt="Sched Graph Image"
src="https://raw.githubusercontent.com/quasiben/dask-scheduler-performance/benchmark-images/assets/4480-20210204-sched-graph.png">

**Comment by jakirkham** [comment]
As PR ( https://github.com/dask/distributed/pull/4480 ) appears to be based on commit ( https://github.com/dask/distributed/commit/08ea96890674d48b90f4e1f92959957e5e362a18 ) as opposed to `master` latest, this should be compared to the results in issue ( https://github.com/quasiben/dask-scheduler-performance/issues/98 )

**Comment by jakirkham** [comment]
More recent run using the same PR based off `master` instead in issue ( https://github.com/quasiben/dask-scheduler-performance/issues/103 )
