### ISSUE TITLE
Missing benchmark run for 20201202

### ISSUE THREAD

**Issue by jakirkham** [quasiben/dask-scheduler-performance#38]
It looks like the nightly benchmark run didn't occur for today. Filing this issue to track.

**Comment by jakirkham** [comment]
AIUI this repo ( https://github.com/quasiben/dask-cuda-benchmarks ) is used to perform the install. Maybe something is going wrong with the install steps. We've had some issues with `pip`'s resolver and development installs recently. So added PR ( https://github.com/quasiben/dask-cuda-benchmarks/pull/35 ) to address those issues. However maybe there are other issues after that step.

**Comment by jakirkham** [comment]
Would it be possible to share the output from the install here, @quasiben? IDK if it contains any sensitive info. If so, a relevant snippet or the scrubbed log would be good.

**Comment by quasiben** [comment]
This most likely do to env creation as @jakirkham noted.  Re-running now

**Comment by jakirkham** [comment]
Resolved. Benchmark now reported here ( https://github.com/quasiben/dask-scheduler-performance/issues/39 ).
