### ISSUE TITLE
Environment level profiling

### ISSUE THREAD

**Issue by jakirkham** [quasiben/dask-scheduler-performance#5]
In an attempt to benchmark the shuffle workload using a different strategy, I tried adding the following to `"${CONDA_PREFIX}/lib/python3.8/sitecustomize.py"`. Normally `sitecustomize.py` is non-existent, but when it is added it is run every time the Python interpreter starts up. More details in [these docs]( https://docs.python.org/3/library/site.html ).

The idea of this code is to startup a `cProfile`-style profiler when the interpreter starts up and let it run until the interpreter shuts down. As we need to tell the profiler to write out its results at shutdown, we register a callback with `atexit`. This way Python will run that callback for us when cleaning up the interpreter. We have it write a file that contains the PID to keep files unique so they don't clash.

```python
import atexit
import cProfile
import os
import sys
import uuid

if not os.path.basename(sys.argv[0]).startswith("gprof2dot"):
    p = cProfile.Profile()
    p.enable()
    atexit.register(p.dump_stats, f"prof_{os.getpid()}.pstat")
```

Doing this with `python shuffle.py`, we can make sure all processes created will save statistics. Just like the benchmark script, we start [the scheduler in its own process]( https://github.com/quasiben/dask-scheduler-performance/blob/04b2db4dfc86f6f924df207ce2d461e8ae2cfff0/run-shuffle.sh#L1 ), [a worker (though we used `--nprocs 1`)]( https://github.com/quasiben/dask-scheduler-performance/blob/04b2db4dfc86f6f924df207ce2d461e8ae2cfff0/run-shuffle.sh#L3 ), and then [the `shuffle.py` script]( https://github.com/quasiben/dask-scheduler-performance/blob/04b2db4dfc86f6f924df207ce2d461e8ae2cfff0/run-shuffle.sh#L5 ).

From this we get 5 different profiler result files. One is just for `shuffle.py`, which simply shows `main` is run. So is uninteresting. Another shows the `Client`. Yet another one shows the `Scheduler`. Finally two shows the `Worker` and its `Nanny`.

With all of these we can pass them to [`gprof2dot`]( https://github.com/jrfonseca/gprof2dot ), which parses the profiler statistics and generates `.dot` files. In turn these can be passed to [Graphviz]( https://graphviz.org ) to generate images of the callgraphs from each of the tasks.

**Comment by quasiben** [comment]
That's really cool!  Should we add this to the repo as well ?  Happy to do that if you think we should.

**Comment by jakirkham** [comment]
Yeah we can do that. Was just documenting the process here so we have it. Also it provides more context for the results here ( https://github.com/quasiben/dask-scheduler-performance/issues/6 ).

**Comment by quasiben** [comment]
Integrated with #2

**Comment by jakirkham** [comment]
Made a similar suggestion for our other benchmarks ( https://github.com/quasiben/dask-cuda-benchmarks/issues/37 ).
